// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/arsync.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArsyncClient is the client API for Arsync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArsyncClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
}

type arsyncClient struct {
	cc grpc.ClientConnInterface
}

func NewArsyncClient(cc grpc.ClientConnInterface) ArsyncClient {
	return &arsyncClient{cc}
}

func (c *arsyncClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, "/arsync.Arsync/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArsyncServer is the server API for Arsync service.
// All implementations must embed UnimplementedArsyncServer
// for forward compatibility
type ArsyncServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	mustEmbedUnimplementedArsyncServer()
}

// UnimplementedArsyncServer must be embedded to have forward compatible implementations.
type UnimplementedArsyncServer struct {
}

func (UnimplementedArsyncServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedArsyncServer) mustEmbedUnimplementedArsyncServer() {}

// UnsafeArsyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArsyncServer will
// result in compilation errors.
type UnsafeArsyncServer interface {
	mustEmbedUnimplementedArsyncServer()
}

func RegisterArsyncServer(s grpc.ServiceRegistrar, srv ArsyncServer) {
	s.RegisterService(&Arsync_ServiceDesc, srv)
}

func _Arsync_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArsyncServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arsync.Arsync/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArsyncServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Arsync_ServiceDesc is the grpc.ServiceDesc for Arsync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arsync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arsync.Arsync",
	HandlerType: (*ArsyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Arsync_Prepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/arsync.proto",
}
